name: filterframework_to_nwb
channels:
- defaults
- conda-forge
- anaconda
dependencies:
- "python >= 3.6"
- pynwb
- hdmf
- pandas
- networkx
- matplotlib
- numpy
- scipy
- python-dateutil
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
- pip
- pip:
  - python-intervals
